"""Add new authors and books

Revision ID: 0fb627bc1871
Revises: c55c085087eb
Create Date: 2023-06-25 04:22:36.502569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb627bc1871'
down_revision = 'c55c085087eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('number_of_pages', sa.Integer(), nullable=True))
    op.drop_column('books', 'number_pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('number_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('books', 'number_of_pages')
    # ### end Alembic commands ###
