"""Add new authors and books

Revision ID: 453137dcaedb
Revises: 
Create Date: 2023-06-25 03:55:17.298892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453137dcaedb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    authors=op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    books=op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number_pages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###
    # Populate the authors table
    authors_data = [
        {'name': 'John Smith',},
        {'name': 'Jane Johnson', },
        {'name': 'John Doe',},
        {'name': 'Jane Doe',},
        {'name': 'Go py',},
    ]
    
    op.bulk_insert( authors, authors_data)


    # Populate the books table
    books_data = [
        {'name': 'Book 1', 'number_pages': 100, 'author_id': 1,},
        {'name': 'Book 2', 'number_pages': 200, 'author_id': 1,} ,
        {'name': 'Book 3', 'number_pages': 300, 'author_id': 2,}
        ]
    op.bulk_insert(books, books_data)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
